# -*- coding: utf-8 -*-
"""qrcode_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/170bca9SKNmM1B1WXXWd4XGYeTesblnVT

### QR Code Generator
Enter the URL you want to convert into a QR code below. After running the cell, the QR code will be displayed, and Also have an option to download it.
"""

import qrcode as qr
import ipywidgets as widgets
from IPython.display import display, Image, clear_output
from google.colab import files

# @title Enter the URL and press Enter to generate QR code
Enter_URL = "https://github.com/shubha0010" # @param {type:"string"}

if url_to_encode:
  qr_img = qr.make(Enter_URL)
  filename = "generated_qrcode.png"
  qr_img.save(filename)

  print(f"QR Code for '{Enter_URL}' generated and saved as '{filename}'.")

  # Display the QR code
  display(Image(filename))

  # Provide download button
  def download_button_handler(obj):
    files.download(filename)

  download_button = widgets.Button(description="Download QR Code")
  download_button.on_click(download_button_handler)
  display(download_button)
else:
  print("Please enter a URL to generate the QR code.")